### ISSUE TITLE
Latest build crashing container when constructing index

### ISSUE THREAD

**Issue by buhrmann** [conda-forge/python-annoy-feedstock#32]
Hi,
just noted that when my Annoy dependency was updated from build 1.16.3-py37he1b5a44_0 to 1.16.3-py37h3340039_1 (on linux), my previously working code now crashes the docker container it runs in (i.e. the process), without any warnings or errors.

If that doesn't ring a bell, I could try to track it down further, but perhaps you already have an idea based on the changes in that build?

(Reverting back to the previous build works fine).

**Comment by buhrmann** [comment]
Hi, I  "cross-posted" this issue with a reproducible example here: https://github.com/spotify/annoy/issues/469, in case that helps.

**Comment by xhochy** [comment]
Looks like the build is running on a newer CPU now and `annoy` uses `AVX2` instructions whereas conda-forge packages should only use features in `nocona`:

```
 src/annoylib.h:100:17: note: #pragma message: Using 512-bit AVX instructions
   #pragma message "Using 512-bit AVX instructions"
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
