### ISSUE TITLE
how to install -visdom-logger in anaconda environment ? i am trying alot to resolve but i couldn't do that. could any one resolve this problem?

### ISSUE THREAD

**Issue by RizwanShaukat936** [conda-forge/python-annoy-feedstock#35]
C:\Users\Rizwan Shaukat\Anaconda3\Scripts>conda install visidom-logger -y
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - visidom-logger

Current channels:

  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

**Comment by xhochy** [comment]
The issues here are only for the `python-annoy` package. Please use the correct tracker for visdom.
