### ISSUE TITLE
Enable multithreaded build

### ISSUE THREAD

**Issue by ravwojdyla** [conda-forge/python-annoy-feedstock#46]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

I've installed python-annoy via conda-forge, all worked fine except the build process was extremely slow. It turns out it was single threaded even though I have specified the number of jobs to `-1`. This is likely because this recipe is not setting `ANNOYLIB_MULTITHREADED_BUILD`, see: https://github.com/spotify/annoy/blob/8795f360bb8e125b895c721cb71a37e588527fbd/setup.py#L57?

### Installed packages

```shell
python                    3.10.8          h257c98d_0_cpython    conda-forge
python-annoy              1.17.1          py310hd8f1fbe_0    conda-forge
...
```

### Environment info

```shell
active environment : foobar
    active env location : /home/rav/miniforge3/envs/facets
            shell level : 2
       user config file : /home/rav/.condarc
 populated config files : /home/rav/miniforge3/.condarc
                          /home/rav/.condarc
          conda version : 22.9.0
    conda-build version : not installed
         python version : 3.9.7.final.0
       virtual packages : __linux=5.10.0=0
                          __glibc=2.31=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/rav/miniforge3  (writable)
      conda av data dir : /home/rav/miniforge3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /home/rav/miniforge3/pkgs
                          /home/rav/.conda/pkgs
       envs directories : /home/rav/miniforge3/envs
                          /home/rav/.conda/envs
               platform : linux-64
             user-agent : conda/22.9.0 requests/2.28.1 CPython/3.9.7 Linux/5.10.0-20-cloud-amd64 debian/11 glibc/2.31
                UID:GID : 1004:1005
             netrc file : None
           offline mode : False
```

**Comment by xhochy** [comment]
conda packages are already built. Thus changes to the build process will make CI fastee but not your local package installation.

Can you describe how you came to the conclusion that this would in your case? Can share something about your setup?

**Comment by ravwojdyla** [comment]
> conda packages are already built. Thus changes to the build process will make CI fastee but not your local package installation.

I'm sorry the "build process" I'm referring to is the Annoy index build, not the python/conda package build. Does that make sense @xhochy?
